version: "3"

services:
  api:
    # Build from /api Dockerfile
    build: ./api
    # Run script to start server
    command: npm run start
    restart: unless-stopped
    ports:
      # port of host/container
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=http://realworld-docker.com
      - MONGO_URL=mongodb://api_db:27017/api
    # starts after
    depends_on:
      - api_db

  api_db:
    image: mongo:latest
    volumes: 
      - mongodb_api:/data/db

volumes:
  mongodb_api:
